blank_issues_enabled: false
contact_links:
  - name: Report a generic issue or idea
    about: If you have a suggestion or bug that doesn't fit in the other templates, let us know here.
    url: https://github.com/opentea-org/OpenTEA/issues/new